In [1]:
#Import the numpy package under the name np
import numpy as np

In [34]:
#Create a null vector of size 10
data = np.zeros((10,10))
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
#Create a vector with values ranging from 10 to 49
import numpy as np
vectore = np.arange(10,49)
vectore

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [4]:
vectore.size

39

In [5]:
#Find the shape of previous array in question 3
vectore.shape

(39,)

In [6]:
vectore.reshape(39,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48]])

In [7]:
#Print the type of the previous array in question 3
type(vectore)

numpy.ndarray

In [8]:
vectore.ndim

1

In [32]:
#Print the numpy version and the configuration
import numpy
print(numpy.__version__)
print(np.show_config())


1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [13]:
#Print the dimension of the array in question 3
import numpy as np
data_three_D = np.array([[[1,2,3,4,11],[5,6,44,7,8],[15,9,10,11,12],[50,13,14,15,16]]])
data_three_D

array([[[ 1,  2,  3,  4, 11],
        [ 5,  6, 44,  7,  8],
        [15,  9, 10, 11, 12],
        [50, 13, 14, 15, 16]]])

In [14]:
data_three_D.ndim

3

In [15]:
data.shape

(10,)

In [16]:
#Create a boolean array with all the True values
import numpy as np
boolen_Array = np.ones((4,3),dtype =bool)
boolen_Array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
#Create a two dimensional array
import numpy as np
two_D = np.array([[1,3,4,9,10],[12,3,6,9,8]])
two_D

array([[ 1,  3,  4,  9, 10],
       [12,  3,  6,  9,  8]])

In [18]:
two_D.ndim

2

In [19]:
#Create a three dimensional array
import numpy as np
three_D = np.array([[[1,3,5,6],[9,4,6,5],[2,7,3,4]]])
three_D


array([[[1, 3, 5, 6],
        [9, 4, 6, 5],
        [2, 7, 3, 4]]])

In [20]:
three_D.ndim

3

In [21]:
#Reverse a vector (first element becomes last)
import numpy as np
vectores = np.arange(1,20)
vectores

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
vectores[-1::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [23]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
null_vector.size

10

In [26]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [27]:
#Create a 3x3 identity matrix
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
matrix.shape

(3, 3)

In [29]:
'''
arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float
'''
import numpy as np
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [30]:
'''
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

'''
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [31]:
'''
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Make an array by comparing both the arrays provided above


'''
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
#if arr1 == arr2:
 #   print(arr1)

In [35]:
#Extract all odd numbers from arr with values(0-9)
import numpy as np
arrays = np.arange(0,9)
arrays[arrays % 2 != 0]


array([1, 3, 5, 7])

In [36]:
#Replace all odd numbers to -1 from previous array

import numpy as np
arrays = np.arange(0,9)
arrays[arrays % 2 == 0]


array([0, 2, 4, 6, 8])

In [39]:
'''
arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12
'''
import numpy as np
arr = np.arange(10)
#arr[5] = 8
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5] = 12
arr[6] = 12
arr[7] = 12

In [41]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
#Create a 2d array with 1 on the border and 0 inside
import numpy as np
arrays = np.diag([1,1,1])
arrays

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
arrays.ndim

2

In [44]:
'''

Difficulty Level Medium

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12
'''
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [46]:
'''
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

'''
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0][0:3] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
import numpy as np
addr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
addr2D


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
addr2D.shape

(2, 5)

In [62]:
addr2D[0][0:5]

array([0, 1, 2, 3, 4])

In [63]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
import numpy as np
addr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
addr2D



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
addr2D[1][1]

6

In [65]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
import numpy as np
arr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
arr2D[:3:,2]

array([2, 7])

In [70]:
#Create a 10x10 array with random values and find the minimum and maximum values
from numpy import random
#a=[10,8,9]
#b=[5,4,3]
a = np.random.randint((10,10))
print('random numbers are ',a)
print(max(a))
print(min(a))


random numbers are  [7 6]
7
6


In [75]:
#Generate a matrix of 20 random values and find its cumulative sum
from numpy import random

x = random.randint(20)
cum_sum = np.cumsum(x)
cum_sum


array([11])

In [78]:
'''
27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b


'''
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.unique((a,b))
common

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
'''
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match
'''
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
positon = np.where((a ==b))
positon

(array([1, 3, 5, 7]),)

In [83]:
'''
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

'''
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],dtype='bool') 
data = np.random.randn(7, 4)
#names
#data
print(data[names != 'will']) 

[[[ 1.38605113  0.65298978 -0.09553276 -0.03536423]
  [-0.56101194 -0.87413671  0.54967122  0.65198776]
  [-0.52102513  1.79152137 -1.97534786  0.03598879]
  [-0.21994006 -0.78747352 -0.88180461 -1.55005428]
  [ 1.1169164   1.8354207   0.25903389 -0.43642981]
  [ 0.2560967  -0.81241624  0.05043265  1.29025779]
  [ 1.02815697 -0.46817788  0.39153575 -1.2427865 ]]]


/home/shahid/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  # This is added back by InteractiveShellApp.init_path()


In [84]:
'''
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe
'''
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'BOb'] 


array([[-0.42543165, -0.76839995,  2.20269333, -0.50003614],
       [ 0.51899716, -0.41809991, -0.61240067,  0.1589652 ],
       [ 1.1490551 ,  0.84850857,  1.01330732, -0.663672  ],
       [ 1.07397955,  0.50114646, -0.71888767, -0.52688202],
       [ 0.09668255, -0.46835999,  0.33308738, -1.08514663],
       [ 0.20200942,  0.81579057,  0.41795211, -2.07804167],
       [ 0.47780118,  1.05549794,  1.1257495 ,  1.05779182]])

In [85]:
data[names == 'Joe'] 

array([[ 0.51899716, -0.41809991, -0.61240067,  0.1589652 ],
       [ 0.20200942,  0.81579057,  0.41795211, -2.07804167],
       [ 0.47780118,  1.05549794,  1.1257495 ,  1.05779182]])

In [86]:
'''
Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
'''
import numpy as np
data = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8, 9, 10, 11, 12, 13, 14, 15]],dtype="float")
data
data.shape

(1, 15)

In [87]:
data.reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [88]:
'''
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
'''
import numpy as np
data = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]],dtype="float")
data.shape

(2, 8)

In [89]:
data.reshape(2,2,4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [101]:
'''
Create an array of size 10, and find the square root of every element in the array, 
if the values less than 0.5, replace them with 0
'''
import numpy as np
import random 
squre_root = np.random.randint(10)
print(squre_root)
print(np.sqrt(squre_root))
print(np.where(squre_root<0.5,0,1))


8
2.8284271247461903
1


In [112]:
'''
Create two random arrays of range 12 and make an array 
with the maximum values between each element of the two arrays

'''
import numpy as np
data=np.array(np.random.rand(12))
data1=np.array(np.random.rand(12))
print('\n',data)
print('\n',data1)
print('\n',np.where(data>data1,data,data1))
print('\n',np.where(data>data,data1,data))


 [0.1127142  0.84953838 0.75123587 0.42772048 0.66844157 0.93773816
 0.99939207 0.32739727 0.07768868 0.7573202  0.59044845 0.30536776]

 [0.70372701 0.87171445 0.76777475 0.38065898 0.76442517 0.46394052
 0.47338195 0.67242694 0.43041435 0.6673844  0.58531826 0.44146881]

 [0.70372701 0.87171445 0.76777475 0.42772048 0.76442517 0.93773816
 0.99939207 0.67242694 0.43041435 0.7573202  0.59044845 0.44146881]

 [0.1127142  0.84953838 0.75123587 0.42772048 0.66844157 0.93773816
 0.99939207 0.32739727 0.07768868 0.7573202  0.59044845 0.30536776]


In [113]:
'''
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!
'''
count = 0
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq  = np.unique(names)
uniq
    
    


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [114]:
'''
From array a remove all items present in array b
'''
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a!=b)
print('\n',np.setdiff1d(a,b))

[ True  True  True  True  True]

 [1 2 3 4]


In [120]:
'''
Generate a matrix of 20 random values and find its cumulative sum
'''
import random

sum1 = np.random.randn(20)
#sum1 = np.cumsum()
print(sum1)


[ 0.21396064 -1.1740525   1.36669629  0.23318577  0.87085653 -1.12164909
  2.23692991 -0.05913737 -0.70675532  1.04495661  0.11229733  0.28414706
  0.40844225 -0.90484496  0.75029737 -0.28733262  0.85803012  0.55342534
 -1.03270581  1.04928855]


In [121]:
'''
x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix
'''
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_prodct = np.dot(x,y)
dot_prodct

array([[ 28.,  64.],
       [ 67., 181.]])