In [1]:
'''
Question:1
Convert a 1D array to a 2D array with 2 rows?
Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
'''
import numpy as np
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
'''
Question:2
How to stack two arrays vertically?
Desired Output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
'''
#in vertically array increase the rows 
import numpy  as np
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
stack_array = np.vstack((a,b))
stack_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
'''
Question:3
How to stack two arrays horizontally?
Desired Output::
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

'''
#in horizoantal incread the columns
import numpy as np
data = np.array([0,1,2,3,4,1,1,1,1,1])
data1 = np.array([5,6,7,8,9,1,1,1,1,1])
stacks= np.hstack((data,data1))
stacks


array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [5]:
'''

Question:4
How to convert an array of arrays into a flat 1d array?
Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
'''
import numpy  as np
data = np.array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],dtype=int)
data



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
'''

Question:5
How to Convert higher dimension into one dimension?
Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
'''
import numpy as np
data = np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
data.reshape(1,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [9]:
'''
Convert one dimension to higher dimension?
Desired Output::
array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

'''
import numpy as np
data = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
data.shape

(15,)

In [10]:
'''
Create 5x5 an array and find the square of an array?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19,15], [ 13, 14, 5,20,18], [ 6, 7, 8,16,17], [ 9, 10, 11,22,21], [12, 13, 14,24,26]])
data

array([[ 0,  1,  2, 19, 15],
       [13, 14,  5, 20, 18],
       [ 6,  7,  8, 16, 17],
       [ 9, 10, 11, 22, 21],
       [12, 13, 14, 24, 26]])

In [11]:
data.shape

(5, 5)

In [12]:
square = np.square(data)
square

array([[  0,   1,   4, 361, 225],
       [169, 196,  25, 400, 324],
       [ 36,  49,  64, 256, 289],
       [ 81, 100, 121, 484, 441],
       [144, 169, 196, 576, 676]])

In [13]:
'''

Question:8
Create 5x6 an array and find the mean?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19,15,24], [ 30,13, 14, 5,20,18], [31, 6, 7, 8,16,17], [ 34,9, 10, 11,22,21], [38,12, 13, 14,24,26]])
data


array([[ 0,  1,  2, 19, 15, 24],
       [30, 13, 14,  5, 20, 18],
       [31,  6,  7,  8, 16, 17],
       [34,  9, 10, 11, 22, 21],
       [38, 12, 13, 14, 24, 26]])

In [14]:
data.mean()

16.0

In [15]:
'''
Question:9
Find the standard deviation of the previous array in Q8?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19,15,24], [ 30,13, 14, 5,20,18], [31, 6, 7, 8,16,17], [ 34,9, 10, 11,22,21], [38,12, 13, 14,24,26]])
stander_devi = np.std(data)
stander_devi


9.563820714895625

In [16]:
'''

Question:10
Find the median of the previous array in Q8?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19,15,24], [ 30,13, 14, 5,20,18], [31, 6, 7, 8,16,17], [ 34,9, 10, 11,22,21], [38,12, 13, 14,24,26]])
medians = np.median(data)
medians


14.5

In [17]:
'''
Question:11
Find the transpose of the previous array in Q8?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19,15,24], [ 30,13, 14, 5,20,18], [31, 6, 7, 8,16,17], [ 34,9, 10, 11,22,21], [38,12, 13, 14,24,26]])
transport = np.transpose(data)
transport

array([[ 0, 30, 31, 34, 38],
       [ 1, 13,  6,  9, 12],
       [ 2, 14,  7, 10, 13],
       [19,  5,  8, 11, 14],
       [15, 20, 16, 22, 24],
       [24, 18, 17, 21, 26]])

In [18]:
'''
Question:12
Create a 4x4 an array and find the sum of diagonal elements?

'''
import numpy as np
data = np.array([[ 0, 1, 2,19], [ 30,13, 14, 5], [31, 6, 7, 8], [10, 11,22,21]])
data

array([[ 0,  1,  2, 19],
       [30, 13, 14,  5],
       [31,  6,  7,  8],
       [10, 11, 22, 21]])

In [19]:
data.shape

(4, 4)

In [20]:
diag = np.diagonal(data)
diag

array([ 0, 13,  7, 21])

In [21]:
sum(diag)

41

In [22]:
'''
Question:13
Find the determinant of the previous array in Q12?
'''
import numpy as np
data = np.array([[ 0, 1, 2,19], [ 30,13, 14, 5], [31, 6, 7, 8], [10, 11,22,21]])
determinat =np.linalg.det((data))
determinat

41115.99999999995

In [23]:
'''
Question:14
Find the 5th and 95th percentile of an array?
'''
import numpy as np
data = np.array([1,5,3,4,8,50,3,6,95,3,6,44,89])
print(np.percentile(data,5))
print(np.percentile(data,95))

2.2
91.39999999999999


In [24]:
'''
Question:15
How to find if a given array has any null values?¶
'''
import numpy as np
data = np.array([1,5,3,4,8,50,3,6,95,3,6,44,89,0,np.nan])
find_null = np.isnan(data)
find_null

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])